apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: teamdagpenger
  name: dp-soknad-orkestrator
  namespace: teamdagpenger
spec:
  ingresses:
    - https://dp-soknad-orkestrator.dev-gcp.nav.cloud.nais.io
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name : soknad-orkestrator
            envVarPrefix: DB
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: elastic