apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: teamdagpenger
  name: dp-soknad-orkestrator
  namespace: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: {{ replicas.max }}
    min: {{ replicas.min }}
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
  leaderElection: true
  kafka:
    pool: {{ kafka.pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name : soknad-orkestrator
            envVarPrefix: DB
        tier: db-custom-1-3840
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: GRUPPER_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: DP_BEHANDLING_SCOPE
      value: {{DP_BEHANDLING_SCOPE}}
    - name: PDL_API_HOST
      value: {{PDL_API_HOST}}
    - name: PDL_API_USER_SCOPE
      value: {{PDL_API_USER_SCOPE}}
    - name: PDL_API_SYSTEM_SCOPE
      value: {{PDL_API_SYSTEM_SCOPE}}
    - name: PERSON_KONTO_REGISTER_SCOPE
      value: {{PERSON_KONTO_REGISTER_SCOPE}}
  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{azure.grupper.saksbehandler}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-brukerdialog-frontend
        - application: dp-saksbehandling-frontend
        {{#if wonderwalled}}
        - application: tokenx-token-generator
          namespace: nais
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        {{/if}}
    outbound:
      rules:
        - application: dp-behandling
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: logging
          namespace: nais-system
      external:
        - host: {{PDL_API_HOST}}
  tokenx:
    enabled: true
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
