apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: teamdagpenger
  name: dp-soknad-orkestrator
  namespace: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  kafka:
    pool: {{kafka_pool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name : soknad-orkestrator
            envVarPrefix: DB
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: CLEAN_ON_STARTUP
      value: "false"
