apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: teamdagpenger
  name: dp-soknad-orkestrator
  namespace: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: {{ replicas.max }}
    min: {{ replicas.min }}
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
  kafka:
    pool: {{ kafka.pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name : soknad-orkestrator
            envVarPrefix: DB
        tier: db-custom-1-3840
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    inbound:
      rules:
        - application: dp-soknad-frontend
        {{#if wonderwalled}}
        - application: tokenx-token-generator
          namespace: aura
        {{/if}}
  tokenx:
    enabled: true
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
