apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: teamdagpenger
  name: dp-soknad-orkestrator
  namespace: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: {{ replicas.max }}
    min: {{ replicas.min }}
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
  kafka:
    pool: {{ kafka.pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name : soknad-orkestrator
            envVarPrefix: DB
        tier: db-custom-1-3840
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  env:
    name: GRUPPER_SAKSBEHANDLER
    value: {{azure.grupper.saksbehandler}}
  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      allowAllUsers: false
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-brukerdialog-frontend
        {{#if wonderwalled}}
        - application: tokenx-token-generator
          namespace: aura
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        {{/if}}
  tokenx:
    enabled: true
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
