openapi: 3.0.0
info:
  title: Søknad Orkestrator API
  version: 1.0.0
  description: API for å opprette søknad, besvare spørsmå og hente neste spørsmål.
  contact:
    name: '#team-dagpenger-brukerdialog'
servers:
  - url: https://dp-soknad-orkestrator.intern.dev.nav.no
    description: dev
  - url: https://dp-soknad-orkestrator.intern.nav.no
    description: prod
paths:
  /soknad/start:
    post:
      summary: Opprett en ny søknad
      responses:
        '201':
          description: Søknad opprettet
          content:
            application/json:
              schema:
                type: string
                format: uuid
  /soknad/{søknadId}/neste:
    get:
      summary: Hent spørsmålsgruppe som har neste ubesvarte spørsmål
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Spørsmålsgruppe med neste ubesvarte spørsmål ble returnert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sporsmalgruppe'
  /soknad/{søknadId}/svar:
    post:
      summary: Post spørsmål med et svar
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sporsmal'
      responses:
        '201':
          description: Besvart spørsmål ble lagret

components:
  schemas:
    Sporsmal: # Spørsmål
      type: object
      properties:
        id:
          type: string
          format: uuid
        tekstnøkkel:
          type: string
        type:
          $ref: '#/components/schemas/SporsmalType'
        svar:
          type: string
          nullable: true
          description: Svar kan være enten en string, boolean, dato eller periode (se Periodesvar) avhengig av hvilken type spørsmål det er.
        gyldigeSvar:
          type: array
          items:
            type: string
          nullable: true
      required:
        - id
        - tekstnøkkel
        - type
    SporsmalType: # SpørsmålType
      type: string
      enum:
        - LAND
        - PERIODE
        - DATO
        - TEKST
        - BOOLEAN
    Sporsmalgruppe: # Spørsmålgruppe
      type: object
      properties:
        id:
          type: integer
        navn:
          $ref: '#/components/schemas/SporsmaalgruppeNavn'
        nesteSpørsmål:
          $ref: '#/components/schemas/Sporsmal'
        besvarteSpørsmål:
          type: array
          items:
            $ref: '#/components/schemas/Sporsmalgruppe'
      required:
        - id
        - navn
        - besvarteSpørsmål
    SporsmaalgruppeNavn: # SpørsmålgruppeNavn
      type: string
      enum:
        - BOSTEDSLAND
    Periodesvar:
      type: object
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
      required:
        - fom




