openapi: 3.0.0
info:
  title: Søknad Orkestrator API
  version: 1.0.0
  description: API for å opprette søknad, besvare opplysninger og hente neste seksjon.
  contact:
    name: '#team-dagpenger-brukerdialog'
servers:
  - url: https://dp-soknad-orkestrator.intern.dev.nav.no
    description: dev
  - url: https://dp-soknad-orkestrator.intern.nav.no
    description: prod
paths:
  /opplysninger/{soknadId}/barn:
    get:
      summary: Hent opplysning om barn
      parameters:
        - in: path
          name: soknadId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BarnResponse'
        '400':
          description: SøknadId mangler eller har feil format
  /opplysninger/{soknadId}/barn/oppdater:
    put:
      summary: Oppdater opplysning om barn
      parameters:
        - in: path
          name: soknadId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OppdatertBarnRequest'
      responses:
        '200':
          description: OK
        '400':
          description: barnetilleggFom og barnetilleggTom må være satt når kvalifisererTilBarnetillegg er true
        '404':
            description: Fant ikke opplysningen som skal oppdateres
        '304':
          description: Opplysningen inneholder ingen endringer, kan ikke oppdatere
  /land:
    get:
      summary: Hent liste med alle land
      responses:
        '200':
          description: Liste med land returnert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Land'
components:
  schemas:
    BarnOpplysning:
      type: object
      properties:
        id:
          type: string
          format: string
        verdi:
          type: string
          format: string
        dataType:
          type: string
          enum:
            - dato
            - land
            - boolsk
            - tekst
        kilde:
          type: string
          enum:
            - soknad
            - register
      required:
        - id
        - verdi
        - dataType
    BarnResponse:
      type: object
      properties:
        barnId:
          type: string
          format: uuid
        opplysninger:
          type: array
          items:
            $ref: '#/components/schemas/BarnOpplysning'
      required:
        - barnId
        - opplysninger
    OppdatertBarnRequest:
      type: object
      properties:
        opplysningId:
          type: string
          format: uuid
        behandlingId:
          type: string
          format: uuid
        oppdatertBarn:
            $ref: '#/components/schemas/OppdatertBarn'
      required:
        - opplysningId
        - behandlingId
        - oppdatertBarn
    OppdatertBarn:
      type: object
      properties:
        barnId:
          type: string
          format: uuid
        fornavnOgMellomnavn:
          type: string
        etternavn:
          type: string
        fodselsdato:
          type: string
          format: date
        oppholdssted:
          type: string
        forsorgerBarnet:
          type: boolean
        kvalifisererTilBarnetillegg:
          type: boolean
        barnetilleggFom:
          type: string
          format: date
        barnetilleggTom:
          type: string
          format: date
        begrunnelse:
          type: string
      required:
        - barnId
        - fornavnOgMellomnavn
        - etternavn
        - fodselsdato
        - oppholdssted
        - forsorgerBarnet
        - kvalifisererTilBarnetillegg
        - begrunnelse
    Opplysning:
      type: object
      properties:
        opplysningId:
          type: string
          format: uuid
        tekstnøkkel:
          type: string
        type:
          $ref: '#/components/schemas/Opplysningstype'
        svar:
          type: string
          nullable: true
          description: Svar kan være enten en string, boolean, dato eller periode (se Periodesvar) avhengig av hvilken type opplysning det er.
        gyldigeSvar:
          type: array
          items:
            type: string
          nullable: true
      required:
        - opplysningId
        - tekstnøkkel
        - type
    Opplysningstype:
      type: string
      enum:
        - land
        - periode
        - dato
        - tekst
        - boolean
    Seksjon:
      type: object
      properties:
        navn:
          $ref: '#/components/schemas/Seksjonsnavn'
        nesteUbesvarteOpplysning:
          $ref: '#/components/schemas/Opplysning'
        besvarteOpplysninger:
          type: array
          items:
            $ref: '#/components/schemas/Opplysning'
        erFullført:
          type: boolean
      required:
        - navn
        - besvarteOpplysninger
        - erFullført
    Seksjonsnavn:
      type: string
      enum:
        - bostedsland
    Periodesvar:
      type: object
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
      required:
        - fom
    Land:
      type: object
      properties:
        alpha3kode:
          type: string
          example: NOR
        navn:
          type: string
          example: Norge
      required:
        - alpha3kode
        - navn
    HtmlDokument:
      type: object
      properties:
        html:
          type: string
          description: Skjemaet bruker har fylt som html, inkludert styling
      required:
        - html



