openapi: 3.0.0
info:
  title: Søknad Orkestrator API
  version: 1.0.0
  description: API for å opprette søknad, besvare opplysninger og hente neste seksjon.
  contact:
    name: '#team-dagpenger-brukerdialog'
servers:
  - url: https://dp-soknad-orkestrator.intern.dev.nav.no
    description: dev
  - url: https://dp-soknad-orkestrator.intern.nav.no
    description: prod
paths:
  /opplysninger/{søknadId}/barn:
    get:
      summary: Hent opplysning om barn
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarnResponse'
        '400':
          description: SøknadId mangler eller har feil format
  /opplysninger/{søknadId}/barn/oppdater:
    put:
      summary: Oppdater opplysning om barn
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OppdatertBarnRequest'
      responses:
        '200':
          description: OK
        '400':
          description: barnetilleggFom og barnetilleggTom må være satt når kvalifisererTilBarnetillegg er true
        '404':
            description: Fant ikke opplysningen som skal oppdateres
        '304':
          description: Opplysningen inneholder ingen endringer, kan ikke oppdatere
  /inntekt/{søknadId}/minsteinntektGrunnlag:
    get:
      summary: Hent opplysinger om minsteinntektgrunnlag for en gitt søknadId
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MinsteinntektGrunnlag'
  /inntekt/{søknadId}/minsteinntektGrunnlag/foreleggingresultat:
    post:
      summary: Post forelegging resultat
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foreleggingresultat'
      responses:
        '200':
          description: OK
    get:
      summary: Hent forelegging resultat
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foreleggingresultat'
  /inntekt/{søknadId}/minsteinntektGrunnlag/foreleggingresultat/journalforing:
    post:
      summary: Post journalforing
      parameters:
        - in: path
          name: søknadId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtmlDokument'
      responses:
        '200':
          description: OK
  /land:
    get:
      summary: Hent liste med alle land
      responses:
        '200':
          description: Liste med land returnert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Land'
components:
  schemas:
    BarnResponse:
      type: object
      properties:
        barnId:
          type: string
          format: uuid
        fornavnOgMellomnavn:
          type: string
        etternavn:
          type: string
        fødselsdato:
          type: string
          format: date
        oppholdssted:
          type: string
        forsørgerBarnet:
          type: boolean
        fraRegister:
          type: boolean
        kvalifisererTilBarnetillegg:
          type: boolean
        barnetilleggFom:
          type: string
          format: date
        barnetilleggTom:
          type: string
          format: date
        begrunnelse:
          type: string
        endretAv:
          type: string
      required:
        - barnId
        - fornavnOgMellomnavn
        - etternavn
        - fødselsdato
        - oppholdssted
        - forsørgerBarnet
        - fraRegister
    OppdatertBarnRequest:
      type: object
      properties:
        barnId:
          type: string
          format: uuid
        fornavnOgMellomnavn:
          type: string
        etternavn:
          type: string
        fødselsdato:
          type: string
          format: date
        oppholdssted:
          type: string
        forsørgerBarnet:
          type: boolean
        kvalifisererTilBarnetillegg:
          type: boolean
        barnetilleggFom:
          type: string
          format: date
        barnetilleggTom:
          type: string
          format: date
        begrunnelse:
          type: string
      required:
        - barnId
        - fornavnOgMellomnavn
        - etternavn
        - fødselsdato
        - oppholdssted
        - forsørgerBarnet
        - kvalifisererTilBarnetillegg
        - begrunnelse
    Opplysning:
      type: object
      properties:
        opplysningId:
          type: string
          format: uuid
        tekstnøkkel:
          type: string
        type:
          $ref: '#/components/schemas/Opplysningstype'
        svar:
          type: string
          nullable: true
          description: Svar kan være enten en string, boolean, dato eller periode (se Periodesvar) avhengig av hvilken type opplysning det er.
        gyldigeSvar:
          type: array
          items:
            type: string
          nullable: true
      required:
        - opplysningId
        - tekstnøkkel
        - type
    Opplysningstype:
      type: string
      enum:
        - land
        - periode
        - dato
        - tekst
        - boolean
    Seksjon:
      type: object
      properties:
        navn:
          $ref: '#/components/schemas/Seksjonsnavn'
        nesteUbesvarteOpplysning:
          $ref: '#/components/schemas/Opplysning'
        besvarteOpplysninger:
          type: array
          items:
            $ref: '#/components/schemas/Opplysning'
        erFullført:
          type: boolean
      required:
        - navn
        - besvarteOpplysninger
        - erFullført
    Seksjonsnavn:
      type: string
      enum:
        - bostedsland
    Periodesvar:
      type: object
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
      required:
        - fom
    Land:
      type: object
      properties:
        alpha3kode:
          type: string
          example: NOR
        navn:
          type: string
          example: Norge
      required:
        - alpha3kode
        - navn
    MinsteinntektGrunnlag:
      type: object
      properties:
        siste12mnd:
          type: string
          example: "100000"
        siste36mnd:
          type: string
          example: "200000"
      required:
        - siste12mnd
        - siste36mnd
    Foreleggingresultat:
      type: object
      properties:
        søknadId:
          type: string
          format: uuid
        bekreftet:
          type: boolean
          description: Om bruker har sagt seg enig i opplysningene
        begrunnelse:
          type: string
          description: Begrunnelse for hvorfor bruker har sagt seg uenig i opplysningene
          example: Det der er feil!
      required:
        - søknadId
        - bekreftet
    HtmlDokument:
      type: object
      properties:
        html:
          type: string
          description: Skjemaet bruker har fylt som html, inkludert styling
      required:
        - html



