name: Deploy dispatch

on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"
  checks: "write"
  pull-requests: "write"

jobs:
  build:
    name: Build and publish Docker image
    uses: ./.github/workflows/build.yaml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-dev:
    name: Deploy to dev
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/vars-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
