name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'alerts/**'
      - '.github/workflows/deploy-staus-no-alert.yaml'
      - '.github/workflows/reviewdog.yaml'

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build installDist --configuration-cache