name: Build and Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.github/workflows/reviewdog.yaml'

permissions:
  contents: "read"
  id-token: "write"
  checks: "write"
  pull-requests: "write"

jobs:
  build:
    name: Build and publish Docker image
    uses: ./.github/workflows/build.yaml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-dev:
    name: Deploy to dev
    needs: [ build ]
    if: github.ref == 'refs/heads/filtrer-data-til-bq'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/vars-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod
    needs: [ build, deploy-dev ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: prod-gcp
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/vars-prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
