name: Publiser OpenAPI docs

on:
  push:
    branches:
      - barneopplysning-enum-id
    paths:
      - openapi/src/main/resources/*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: 'openapi/src/main/resources/'
      - id: deployment
        uses: actions/deploy-pages@v4